backend:
  name: 'git-gateway'
  branch: 'master'
local_backend: true
media_folder: 'hosting/public/uploads'
public_folder: '/uploads'
site_url: 'https://suikou.vercel.app'
display_url: 'https://suikou.vercel.app'
show_preview_links: true
locale: 'ja'
collections:
  - name: 'news-post'
    label: 'お知らせ'
    folder: 'hosting/public/collections/news-posts'
    extension: 'md'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: 'title_en'
    summary: '{{title}} - {{date}}'
    fields:
      - name: 'title'
        label: '記事のタイトル'
        widget: 'string'
      - name: 'title_en'
        label: '記事のタイトル（英語）'
        widget: 'string'
      - name: 'date'
        label: '執筆日'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: 'YYYY-MM-DD'
        time_format: false
      - name: 'body'
        label: '内容'
        widget: 'markdown'
      - name: 'external_url'
        label: '外部のリンク（任意）'
        widget: 'string'
      - name: 'image'
        label: '画像ファイル（任意）'
        widget: 'image'
      - name: 'image_a'
        label: '更に画像ファイル（任意）'
        widget: 'image'
  - label: 'メディア'
    name: 'media-posts'
    folder: 'hosting/public/collections/media-posts'
    extension: 'md'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: 'title_en'
    summary: '{{title}} - {{date}}'
    fields:
      - name: 'title'
        label: '記事のタイトル'
        widget: 'string'
      - name: title_en
        label: '記事のタイトル（英語）'
        widget: 'string'
      - name: 'date'
        label: '執筆日'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: 'YYYY-MM-DD'
        time_format: false
      - name: 'image'
        label: '画像ファイル'
        widget: 'image'
  - name: 'class-posts'
    identifier_field: 'title_en'
    label: '授業'
    label_singular: '全ての授業'
    description: 'eラーニングを公開しています。'
    folder: 'hosting/public/collections/class-posts'
    create: true
    extension: 'md'
    format: 'frontmatter'
    preview_path: 'classes/'
    slug: 'title_en'
    summary: '{{title}} - {{date}}'
    fields:
      - name: 'title'
        label: '記事のタイトル（日本語）'
        widget: 'string'
      - name: 'title_en'
        label: '記事のタイトル（英語）'
        widget: 'string'
      - name: 'date'
        label: '執筆日'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: 'YYYY-MM-DD'
        time_format: false
      - name: 'body'
        label: '内容'
        widget: 'markdown'
  - name: 'feedbacks'
    label: 'フィードバック'
    folder: 'hosting/public/collections/feedbacks'
    extension: 'md'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: 'title_en'
    summary: '{{title}} - {{date}}'
    fields:
      - name: 'title'
        label: '記事のタイトル'
        widget: 'string'
      - name: 'title_en'
        label: '記事のタイトル（英語）'
        widget: 'string'
      - name: 'date'
        label: '執筆日'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: 'YYYY-MM-DD'
        time_format: false
      - name: 'body'
        label: '内容'
        widget: 'markdown'
  - name: 'books'
    label: '書籍'
    create: true
    extension: 'md'
    preview_path: 'books/{{slug}}'
    folder: 'hosting/public/collections/books'
    format: 'frontmatter'
    identifier_field: 'title_en'
    summary: '{{title}}'
    fields:
      - name: 'title'
        label: '本のタイトル（日本語）'
        widget: 'string'
      - name: 'title_en'
        label: '本のタイトル（英語）'
        widget: 'string'
      - name: 'external_url'
        label: '購入先のリンク'
        widget: 'string'
      - name: 'image'
        label: '画像ファイル'
        widget: 'image'
  - name: 'pages'
    label: 'その他ページ'
    files:
      - name: 'about'
        label: 'About Page'
        file: 'site/content/about.yml'
        fields:
          - name: 'title'
            label: 'Title'
            widget: 'string'
          - name: 'intro'
            label: 'Intro'
            widget: 'markdown'
          - name: 'team'
            label: 'Team'
            widget: 'list'
            fields:
              - name: 'name'
                label: 'Name'
                widget: 'string'
              - name: 'position'
                label: 'Position'
                widget: 'string'
              - name: 'photo'
                label: 'Photo'
                widget: 'image'
